// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzhqjqzqzpucxrvqvsgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6aHFqcXpxenB1Y3hydnF2c2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Nzc4MTEsImV4cCI6MjA3NzQ1MzgxMX0.GcClec8yiTtf12KtCOKl7XstuzkI39JakEJFKIRIJkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});